name: Create Pyrrha View

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install botok
          
      - name: Create Orphand Branch
        run: git checkout --orphan Pyrrha
        
      - name: Create Pyrrha View
        shell: python
        run: |
          import csv
          from pathlib import Path
          import botok

          # paths
          pecha_id = Path.cwd().name
          base_path = Path.cwd() / f"{pecha_id}.opf" / "base"
          assert base_path.is_dir()

          # pyrrha format
          cols_name = ["form", "lemma", "POS", "morph"]
          def save_to_pyrrha_format(tokens, output_fn: Path):
              with output_fn.open("w") as out_file:
                  tsv_writer = csv.writer(out_file, delimiter="\t")
                  tsv_writer.writerow(cols_name)
                  for token in tokens:
                      tsv_writer.writerow(
                          [token.text_cleaned, token.lemma, token.pos]
                      )

          # tokenize with botok as save in Pyrrha format
          wt = botok.WordTokenizer()
          for base_fn in base_path.iterdir():
              tokens = wt.tokenize(base_fn.read_text())
              output_fn = Path.cwd() / f"{base_fn.stem}.tsv"
              save_to_pyrrha_format(tokens, output_fn)

          # Create readme
          readme_path = Path.cwd() / "README.md"
          readme_content = f"Config\n----\n- Tokenizer: `botok-v{botok.vars.__version__}`"
          readme_path.write_text(readme_content)

      - name: Clean up
        run: |
          ls
          rm -rf *.opf
          rm -rf readme.md
          
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: created pyrrha view
          branch: Pyrrha
          create_branch: true
